---
title: "Bird_Analysis"
author: "Reagan Edgren"
date: "12/6/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(GGally)
library(ggpubr)
```



```{r}
bird_data <- read_table("~/GitHub/stat-415-final-project/data/britain_species.txt", col_names = FALSE)

#Modified path
#bird_data <- read_table("data/britain_species.txt", col_names = FALSE)

bird_data %>% 
  rename(island = X1,
         area = X2,
         elevation = X3,
         soil = X4,
         latitude = X5,
         distance = X6,
         species = X7) %>%
  mutate(area = as.double(area),
         elevation = as.integer(elevation),
         soil = as.integer(soil),
         latitude = as.double(latitude),
         distance = as.double(distance),
         species = as.integer(species)) -> bird_data
bird_data
```


Estimated regression function
```{r}
bird.reg <- lm(species ~ area + elevation + soil + latitude + distance, 
               data = bird_data)

summary(bird.reg)
anova(bird.reg)
```

```{r}
plot(bird.reg$residuals ~ bird_data$species)
abline(0,0)
```

correlation regression

```{r}
bird_data %>%
  select(area,elevation,soil,distance,species) -> bird_cor
cor(bird_cor, use = "complete.obs")
```

```{r}



# ggarrange(area1, area2, elev, soil, dis, spe, lat,
#           ncol = 2, nrow = 4)
bird_data %>%
  select(species, area, elevation, distance, soil, latitude) %>%
  ggpairs()

```




can we get rid of latitude (partial F)

```{r}
bird_nolat <- lm(species ~ area + elevation + soil + distance, 
               data = bird_data)

anova(bird_nolat, bird.reg)
```

```{r}
bird_noarea <- lm(species ~ latitude + elevation + soil + distance, 
               data = bird_data)

anova(bird_noarea, bird.reg)

bird_noelevation <- lm(species ~ latitude + area + soil + distance, 
               data = bird_data)

anova(bird_noelevation, bird.reg)

bird_nodistance <- lm(species ~ latitude + elevation + soil + area, 
               data = bird_data)

anova(bird_nodistance, bird.reg)
```

```{r}
bird_nolat <- lm(species ~ area + elevation + soil + distance, 
               data = bird_data)

anova(bird_nolat, bird.reg)

bird_nosoil <- lm(species ~ latitude + elevation + area + distance, 
               data = bird_data)

anova(bird_nosoil, bird.reg)
```




```{r}
bird_no <- lm(species ~ latitude + soil, 
               data = bird_data)

anova(bird_no, bird.reg)
```







stepwise regression (david)





```{r}

```























